#!/usr/bin/env python3
"""community_pack_markdown — renders docs/community-packs.md's Game/
Console/Author/Date/👍 table for the community pack catalog (split out of
`generate_community_pack_catalog.py` per ADR-0138 §35's 200-line-per-file
guardrail).

The table is 👍-ordered and carries `POPULARITY_NOTE` instead of the former
"Most popular" section, which re-listed the very same packs; the Link /
Submitted by / Category / External assets columns were dropped with it,
the Link one folded into the 👍 cell so a reader lands where votes are cast.

Depends on nothing outside the stdlib (never on `mei_catalog_entry` or the
facade -- ADR-0138 §24's leaf/half split); it stopped needing `mei_rules`
when the Status->display-text `category_from_status` mapping went away with
the Category column.

`build_row` takes the caller-derived `issue_number`/`status` directly
(instead of re-deriving them from a raw Project item, which would require
importing the facade's `item_issue_number`/`item_status` and create a
back-import between the two split halves).

stdlib only.
"""
from __future__ import annotations

import re

CONSOLE_LABELS = {"nes", "snes", "gb", "gbc", "sms", "other"}
TABLE_HEADER = "| Game | Console | Author | Date | 👍 (click to vote) |"
TABLE_SEP = "|---|---|---|---|---|"
TITLE = "# Community Packs"
INTRO = ("Catalog generated automatically from the \"MesenCE Community\n"
         "Packs\" board (Project 3). <br/>\n"
         "Do not edit this file manually — it is\n"
         "overwritten by `.github/workflows/community-pack-catalog.yml`.")
# Replaces the former standalone "Most popular" section, which restated the
# same rows the table already carries now that it is 👍-ordered. Framed as an
# invitation to vote rather than a disclaimer, while still stating outright
# that nothing here comes from usage telemetry.
POPULARITY_NOTE = (
    "Packs are ranked by community 👍 votes. Try a pack, and if you like it, give\n"
    "it a 👍 — your vote helps others discover the community’s favorites. Every\n"
    "submitted pack starts with one vote from its contributor. No usage telemetry\n"
    "is collected.")


def escape_table_cell(value):
    """Collapses whitespace/newlines and escapes '|' for a Markdown table cell."""
    return re.sub(r"\s+", " ", str(value)).replace("|", "\\|").strip()


def thumbs_up_count(details):
    """Defensive sum of THUMBS_UP reactions from reactionGroups."""
    for group in details.get("reactionGroups") or []:
        if group.get("content") == "THUMBS_UP":
            users = group.get("users") or {}
            return users.get("totalCount", 0)
    return 0


def console_from_labels(labels):
    for label in labels or []:
        name = (label.get("name") or "").strip().lower()
        if name in CONSOLE_LABELS:
            return name
    return "?"


#ADR-0152: a row whose artifact carries reviewed known-missing declarations is
#marked in the table rather than given a column of its own -- the case is rare,
#and an almost-empty column would cost every reader more than it tells them.
ERRATA_MARK = " †"
ERRATA_NOTE = (
    "† This pack references one or more files it does not ship. The gap was\n"
    "checked and declared by MesenCE validation — **not by the pack's author** —\n"
    "so the pack is listed and installs normally; the emulator skips the missing\n"
    "entries at load. `docs/community-packs.json` names each one, with a link to\n"
    "where it was reviewed."
)


def build_row(issue_number, status, details, form, errata_count=0):
    """Builds a Markdown catalog row from the caller-derived issue number/
    Status and the fetched issue details + Issue Form fields.

    "Author" is the pack's own credits as discovered by the classify step and
    stored in mep-meta `author` (the Issue Form has no author field since
    b62f0bbc), never the GitHub login that opened the issue -- whoever
    submits a pack is not necessarily its author -- and falls back to "?"
    when mep-meta carries none. `status` no longer reaches the table (the Category column was
    dropped) but stays in the signature: it is what an empty row renders for.
    """
    if issue_number is None:
        return {"jogo": "(no issue)", "console": "?", "autor": "?",
                "data": "?", "url": "", "thumbs_up": 0, "errata_count": 0}
    credits = (form.get("credits") or "").strip() or "?"
    return {
        "jogo": escape_table_cell(form["game"]),
        "console": escape_table_cell(form["console"]),
        "autor": escape_table_cell(credits),
        "data": (details.get("createdAt") or "?")[:10],
        "url": details.get("url") or "",
        "thumbs_up": thumbs_up_count(details),
        "errata_count": errata_count,
    }


def render_table(rows):
    """Renders the table 👍-first: `sorted(rows, key=lambda r: r['thumbs_up'],
    reverse=True)` replaces the former standalone "Most popular" section,
    which listed the very same packs a second time."""
    lines = [TABLE_HEADER, TABLE_SEP]
    if not rows:
        lines.append("| _no packs accepted yet_ | | | | |")
    for row in sorted(rows, key=lambda r: r["thumbs_up"], reverse=True):
        # The 👍 count carries the link to the submission issue (the former
        # standalone Link column): a reader who wants to vote lands exactly
        # where the reaction is added.
        votes = f"[👍 {row['thumbs_up']}]({row['url']})" if row["url"] else f"👍 {row['thumbs_up']}"
        mark = ERRATA_MARK if row.get("errata_count") else ""
        lines.append(
            f"| {row['jogo']}{mark} | {row['console']} | {row['autor']} | "
            f"{row['data']} | {votes} |"
        )
    if any(row.get("errata_count") for row in rows):
        lines.extend(["", ERRATA_NOTE])
    return "\n".join(lines)


def build_markdown(rows):
    return "\n\n".join([TITLE, INTRO, render_table(rows), POPULARITY_NOTE]) + "\n"
