#!/usr/bin/env python3
"""community_pack_markdown — renders docs/community-packs.md's Link/Game/
Console/Author/Submitted by/Category/Date/👍 + External assets table and its "Most
popular" section for the community pack catalog (split out of
`generate_community_pack_catalog.py` per ADR-0138 §35's 200-line-per-file
guardrail).

Depends only on the stdlib-only leaf `mei_rules` (never on
`mei_catalog_entry` or the facade -- ADR-0138 §24's leaf/half split): a
row's `category_from_status` mapping is Status->display-text (e.g. "Full
MEP"), a different pairing than `mei_rules.STATUS_TO_KIND`'s Status->kind,
but both derive their Status literals from the same
`mei_rules.STATUS_TO_KIND` keys rather than a second hardcoded copy.

`build_row` takes the caller-derived `issue_number`/`status` directly
(instead of re-deriving them from a raw Project item, which would require
importing the facade's `item_issue_number`/`item_status` and create a
back-import between the two split halves).

stdlib only.
"""
from __future__ import annotations

import re

import mei_rules

CONSOLE_LABELS = {"nes", "snes", "gb", "gbc", "sms", "other"}
TABLE_HEADER = ("| Link | Game | Console | Author | Submitted by | Category | Date "
                "| 👍 | External assets |")
TABLE_SEP = "|---|---|---|---|---|---|---|---|---|"
TITLE = "# Community Packs"
INTRO = ("Catalog generated automatically from the \"MesenCE Community\n"
         "Packs\" board (Project 3). <br/>\n"
         "Do not edit this file manually — it is\n"
         "overwritten by `.github/workflows/community-pack-catalog.yml`.")

# Derived FROM mei_rules.STATUS_TO_KIND -- see module docstring.
_KIND_TO_STATUS = {kind: status for status, kind in mei_rules.STATUS_TO_KIND.items()}
STATUS_MEP_COMPLETO = _KIND_TO_STATUS["mep"]
STATUS_HD_PARCIAL = _KIND_TO_STATUS["hd-legacy"]


def escape_table_cell(value):
    """Collapses whitespace/newlines and escapes '|' for a Markdown table cell."""
    return re.sub(r"\s+", " ", str(value)).replace("|", "\\|").strip()


def thumbs_up_count(details):
    """Defensive sum of THUMBS_UP reactions from reactionGroups."""
    for group in details.get("reactionGroups") or []:
        if group.get("content") == "THUMBS_UP":
            users = group.get("users") or {}
            return users.get("totalCount", 0)
    return 0


def console_from_labels(labels):
    for label in labels or []:
        name = (label.get("name") or "").strip().lower()
        if name in CONSOLE_LABELS:
            return name
    return "?"


def category_from_status(status):
    if status == STATUS_MEP_COMPLETO:
        return "Full MEP"
    if status == STATUS_HD_PARCIAL:
        return "Partial HD"
    return status or "?"


def build_row(issue_number, status, details, form, has_deps=False):
    """Builds a Markdown catalog row from the caller-derived issue number/
    Status and the fetched issue details + Issue Form fields.

    Author and submitter are distinct: "Author" is the Issue Form's
    "Author/credits" answer (who made the pack), while "Submitted by" is the
    GitHub login that opened the issue -- whoever submits a pack is not
    necessarily its author. Author falls back to "?" when the form field is
    absent, never to the submitter's login.
    """
    if issue_number is None:
        return {"jogo": "(no issue)", "console": "?", "autor": "?", "submissor": "?",
                "categoria": category_from_status(status), "data": "?", "url": "",
                "thumbs_up": 0, "external_assets": ""}
    submitter = (details.get("author") or {}).get("login") or "?"
    credits = (form.get("credits") or "").strip() or "?"
    return {
        "jogo": escape_table_cell(form["game"]),
        "console": escape_table_cell(form["console"]),
        "autor": escape_table_cell(credits),
        "submissor": escape_table_cell(submitter),
        "categoria": category_from_status(status),
        "data": (details.get("createdAt") or "?")[:10],
        "url": details.get("url") or "",
        "thumbs_up": thumbs_up_count(details),
        "external_assets": "yes" if has_deps else "",
    }


def render_table(rows):
    lines = [TABLE_HEADER, TABLE_SEP]
    if not rows:
        lines.append("| _no packs accepted yet_ | | | | | | | | |")
    for row in rows:
        link = f"[link]({row['url']})" if row["url"] else "-"
        lines.append(
            f"| {link} | {row['jogo']} | {row['console']} | {row['autor']} | "
            f"{row['submissor']} | {row['categoria']} | {row['data']} | "
            f"{row['thumbs_up']} | {row['external_assets']} |"
        )
    return "\n".join(lines)


def render_popular_section(rows):
    lines = ["## Most popular", "",
             "_Ranked by 👍 reactions on the submission issue. Validation seeds one 👍_",
             "_per submission (submitting a pack is itself an endorsement), so every_",
             "_listed pack starts at 1. This is a popularity proxy, not a real usage_",
             "_metric — no usage telemetry is collected by this project._", ""]
    ranked = sorted(rows, key=lambda r: r["thumbs_up"], reverse=True)
    if not ranked or ranked[0]["thumbs_up"] == 0:
        lines.append("_no packs with reactions yet._")
        return "\n".join(lines)
    for row in ranked:
        if row["thumbs_up"] <= 0:
            continue
        link = f"[{row['jogo']}]({row['url']})" if row["url"] else row["jogo"]
        lines.append(f"- {link} — 👍 {row['thumbs_up']}")
    return "\n".join(lines)


def build_markdown(rows):
    return "\n\n".join([
        TITLE,
        INTRO,
        render_table(rows),
        render_popular_section(rows),
    ]) + "\n"
