name: Run tests

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1

jobs:
  windows:
    if: ${{ (github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository) }}
    strategy:
      matrix:
        platform: [
          {netversion: 10.x, targetframework: net10.0, aot: false, singleFile: true}
        ]
      fail-fast: false
    runs-on: windows-2025-vs2026

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Install .NET Core
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: ${{ matrix.platform.netversion }}

      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v3
        with:
          msbuild-architecture: x64

      - name: Restore packages
        run: dotnet restore -p:TargetFramework="${{ matrix.platform.targetframework }}" -r win-x64 -p:PublishAot="${{ matrix.platform.aot }}" -p:BuildWithNetFrameworkHostedCompiler=true

      - name: Build Mesen
        run: msbuild -nologo -m -p:Configuration=Release -p:Platform=x64 -t:Clean,PGOHelper -p:TargetFramework="${{ matrix.platform.targetframework }}"

      - name: Checkout MesenTests repo
        uses: actions/checkout@v6
        with:
          repository: nesdev-org/MesenTests
          path: ./bin/win-x64/Release/Tests

      - name: Run CI Tests
        run: ./bin/win-x64/Release/PGOHelper.exe "./bin/win-x64/Release/Tests" citests
 
      - name: Upload screenshots for failures
        if: ${{ failure() }}
        uses: actions/upload-artifact@v7
        with:
          name: Screenshots
          path: ./bin/win-x64/Release/Tests/MesenHomeFolder/Screenshots/